apiVersion: v1
kind: Secret
metadata:
  name: task-saas-secret
  namespace: task-saas
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/task_saas?schema=public
  JWT_ACCESS_SECRET: change-me-access
  JWT_REFRESH_SECRET: change-me-refresh
  POSTGRES_PASSWORD: postgres
