apiVersion: v1
kind: Secret
metadata:
  name: zenith-secret
  namespace: zenith
type: Opaque
stringData:
  DATABASE_URL: "postgresql://zenith:zenithpass@postgres.zenith.svc.cluster.local:5432/zenith?schema=public"
  REDIS_URL: "redis://redis.zenith.svc.cluster.local:6379"
  JWT_ACCESS_SECRET: "replace_me"
  JWT_REFRESH_SECRET: "replace_me"
